### ISSUE TITLE
make_shields.sh heldover from OSM Bright

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-high-contrast.tm2#1]
[This doc snippet](https://github.com/mapbox/mapbox-studio-highcontrast.tm2/blob/master/labels.mss#L328-L329) seems redundant given the direct [use of svg](https://github.com/mapbox/mapbox-studio-highcontrast.tm2/blob/master/labels.mss#L336), and the script isn't available in the codebase anyway.

**Comment by amyleew** [comment]
Looks like this has been removed.

**Comment by wboykinm** [comment]
:+1:
