### ISSUE TITLE
Alleys overlap buildings

### ISSUE THREAD

**Issue by talllguy** [mapbox/mapbox-studio-high-contrast.tm2#4]
It appears that alleys or other `highway=service` ways are rendered in an all-white opaque line that overlaps other features, such as address numbers or building footprints. This is more pronounced on Retina displays.

Here is an example around [Federal Hill](http://www.openstreetmap.org/#map=18/39.27822/-76.61006) in Baltimore. The red arrows are mine. There are a number of "alley streets" there, which seem to exacerbate the issue. Look at [Hamburg Street](http://www.openstreetmap.org/way/6006124) for instance.

![2015-08-17 15_59_10-mapbox _ design and publish beautiful maps](https://cloud.githubusercontent.com/assets/1827881/9314807/432198c4-44f9-11e5-8c09-802a2d9dd030.png)

**Comment by amyleew** [comment]
@talllguy - thanks for the feedback! 

I've updated this road styling by adding `class=service`. Also pulled in the `class=service` labels where available and darkened `housenum_label`. https://github.com/mapbox/mapbox-studio-high-contrast.tm2/commit/2b20294d729e72507dfdc99080013cd4e5a9eda8

![image](https://cloud.githubusercontent.com/assets/4587826/10741490/6d4c2286-7bfe-11e5-935e-277eb42b3900.png)

**Comment by talllguy** [comment]
@amyleew wow this looks great!! Thanks for the fix.
