### ISSUE TITLE
mapbox-owners

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-high-contrast.tm2#5]
@amyleew would you mind running mapbox-owners for this project so others can publish to npm?

https://github.com/mapbox/mapbox-owners

**Comment by amyleew** [comment]
Updated @yhahn 

![image](https://cloud.githubusercontent.com/assets/4587826/10740894/2b8bba4e-7bfb-11e5-932f-a07b0f989e4b.png)

**Comment by yhahn** [comment]
awesome thank you
